[tool.poetry]
name = "bert-clef-diff"
version = "0.1.0"
description = ""
authors = ["Aaron Fletcvher"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas007 = "^1.0.0"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
